name: nf-schema-builder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - typer>=0.15.1
  - jsonschema>=4.20.0
  - pyyaml>=6.0.1
  # Development dependencies
  - pytest>=8.1.1
  - pytest-cov>=4.1.0
  - pytest-sugar>=1.0.0
  - ruff>=0.9.2
  - mypy>=1.14.1
  - types-jsonschema>=4.20.0
  - types-PyYAML>=6.0.1
  - pre-commit>=3.5.0
  - pip:
      - -e .
